# general
title: London Jam Cam Mosaics
author: Sergiu Tripon
description: ""
timezone: Europe/London

# urls
url: "http://sergiu-tripon.com"
baseurl: "/london-jam-cam-mosaics"

# exclude
exclude:
- node_modules
- Gruntfile.js
- package.json
- README.md